language: node_js
node_js:
- '6'
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: ans4175@gmail.com
  api_key:
    secure: LXc97vMNrRTixzGt0LZmLQtthSaSyGxuq0x1jaQLnN9jXLH7PkxKB6PU+muBKzyfklReEck9RBkC/42RaJeyFzjMjmLrD7McTElJNyzOEeAx4aRz1NfEYzhJM9Y1xxJNgrufG/xfTPyCq4PhSNHpT/X8E3grU/uj4ZtdHxcDfykjt21u2Nk33+Fh1TeWzcTzfrDix371T68gzlwg0LHyVeMVXLH4GJmBKFfrccR+/jwIDfVoydnBviDUAsPJOQT39Cgxlqk0y6oiOTAFRu04o6awwFlZDvd4/xfUvsztBuH0kSOcvDMxlbtYBJzLic13lBNokRcLvCmgTRYwnF/T97lIVQoIfpUVWfCn245Ik2Tj3N/Hm4h44DoRYPtgrty5PpSDH+E4MF83G1UD3m6TeN9J4yZD2KXxceAlaJBG4OagB2gE5XApJ0aoBdUx+ZJCy3qh4GqeUE7zEwAVNXJ8aETzEp19VLI79E/I5K9V27nOYYmepMI4cKiEvdRQiG/cJJCpxp4S5/vmDLeKzUYIeF/sxt80xLxjuvMcVHmWEPP8KcVoE9W+cRzPolrOkTweMLmjNnP4WJ15+QXLcnTnblxPrlZD/uiv7MloypNXmTfesXp1pR40TXMpUlu7kI23tuglUAjWfDnipeEFe0xAJaeWPvbzcIAJ2y6b+xSWeTk=
  on:
    tags: true
